plugin: aws_ec2

aws_access_key: AKIATB7Q2CORUFFIEZOR
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
